##### Numpy


In [1]:
import numpy as np
a=np.array([5,6,7])
print (a)

[5 6 7]


In [3]:
b=np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [2]:
c=np.zeros((3,4))
print (c)
#Full 
c=np.full((2,3),10)
print(c)
# RAndomly created - Dynamic in nature 
s= np.random.random((3,2))
print(s)
# Freeze the randomess- used to generate same random numbers
np.random.seed(41) 
np.random.sample((3,2))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10 10 10]
 [10 10 10]]
[[0.05626263 0.11632123]
 [0.73100737 0.54706138]
 [0.08985604 0.54036005]]


array([[0.25092362, 0.04609582],
       [0.67681624, 0.04346949],
       [0.1164237 , 0.60386569]])

In [3]:
# Randomly generating chars
import string
[string.ascii_uppercase[i]  for i in range(5)]

# Randomly generating names
import names
dir(string)
np.array({names.get_first_name() for i in range (5)})

array({'William', 'Jonathan', 'Edith', 'Deanna', 'Velma'}, dtype=object)

In [4]:
#between 10 to 100
np.random.randint(10,100,(3,5))

# random with decimal , we dont have a function
np.around(np.random.randint(10,100,(2,2)) + np.random.sample((2,2)),2)

#Range
np.arange(10)
print(np.arange(10,20))
np.arange(10,30,2)

#Reshaping 1D to 2D
np.arange(10,20).reshape((5,2)) # Product of R and Cshould be equal to total elements

[10 11 12 13 14 15 16 17 18 19]


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [3]:
d=np.arange(1,40,2)
print(d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [7]:
# Linearly separated values - Start , ENd  No.of Values between , equal spaced
d=np.linspace(1,40,10, dtype=int)
print(d)
np.linspace(1,10,5)

[ 1  5  9 14 18 22 27 31 35 40]


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
e=np.full((4,4),6)
print (e)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [16]:
f=np.random.random((3,5))
print (f)

[[0.59303356 0.66716937 0.65968593 0.66296804 0.53657659]
 [0.05985183 0.51030451 0.33192943 0.1771687  0.66723132]
 [0.86326328 0.29675109 0.51835085 0.20295781 0.52552093]]


## Inspection

In [5]:
a=np.array([[1,2,3,4],[2,3,6,7]])
print (a)

[[1 2 3 4]
 [2 3 6 7]]


In [6]:
print(a.shape)

(2, 4)


In [7]:
a.shape=(4,2)

In [8]:
print(a)

[[1 2]
 [3 4]
 [2 3]
 [6 7]]


In [10]:
b=np.array([1,2,3,4])
print(a.ndim)

1


In [11]:
print(a.size)

3


### Maths in Numpy

In [9]:
print (np.sum([[2,3],[4,6]], axis=1))

[ 5 10]


In [31]:
print(np.subtract([2,3],[4,6]))

[-2 -3]


In [33]:
print(np.multiply([2,3],[4,6]))

[ 8 18]


In [34]:
print(np.divide([2,3],[4,6]))

[0.5 0.5]


In [40]:
print(np.sin(a),np.exp(a))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [ 0.90929743  0.14112001]
 [-0.2794155   0.6569866 ]] [[   2.71828183    7.3890561 ]
 [  20.08553692   54.59815003]
 [   7.3890561    20.08553692]
 [ 403.42879349 1096.63315843]]


In [8]:
c= np.array([[1,2,3], 
            [4,8,5]])
c.mean(axis=1)


array([2.        , 5.66666667])

# Numpy Exercises

In [11]:
#Create a numpy array of size 10, filled with zeros.

z=np.zeros([2,2])
print(z)

# Create a numpy array with values ranging from 10 to 49

r = np.arange(10,49)
print(r)

#Create a numpy matrix of 2*2 integers, filled with ones.

i=np.ones([2,2], dtype=int)
print(i)

#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

X = np.arange(4, dtype=int)
print(X)
np.ones_like(X)

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

Y = np.arange(4, dtype=int)

np.zeros_like(X)

# Create a numpy matrix of 4*4 integers, filled with fives.
f = np.array([[1,1,1,1],
             [1,1,1,1],
             [1,1,1,1],
             [ 1,1,1,1]])
f= f*5
print(f)

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
s = np.array([[2,3], [6,2]], dtype=int)
print(s)
np.ones_like(s) * 7

[[0. 0.]
 [0. 0.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[1 1]
 [1 1]]
[0 1 2 3]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[2 3]
 [6 2]]


array([[7, 7],
       [7, 7]])

In [16]:
#Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
i=np.identity(3,dtype=int)
np.ones_like(i)

#Create a numpy array, filled with 3 random integer values between 1 and 10.
np.linspace(1,10,3, dtype=int)
print(np.random.randint(100, size=3))

#Create a 3*3*3 numpy matrix, filled with random float values.
print(np.random.randn(3,3,3))

#Given the X python list convert it to an Y numpy array
x=[4,6,9,3]
np.array(x)

#Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

#Create a numpy array with numbers from 1 to 10
np.arange(1,11)

#Create a numpy array with the odd numbers between 1 to 10
np.arange(1,11,2)

#Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1,11)[::-1]

#Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape(3,3)

#Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

[26 25  8]
[[[-0.1277581  -0.07646054 -0.12367524]
  [-0.10427345 -0.43712785 -0.38752089]
  [-0.66532953 -0.5290061   0.72228169]]

 [[-0.99984093 -0.37821309 -1.69428866]
  [-0.12220507 -0.82928812 -2.16409049]
  [ 0.20874301  1.3467559  -1.27275841]]

 [[ 0.54732139  0.47354037 -0.10499787]
  [-0.23553402 -1.14088765  0.86107794]
  [ 0.05173874 -0.01557364 -0.18622343]]]
[5 2 3] 2563456843568
[5 2 3] 2563478892240
800 bytes


In [22]:
#Given the X numpy array, show it's first element
x=np.array([1,2,3,7,9,4])
x[0]

#Given the X numpy array, show it's last element
x[-1]

#Given the X numpy array, show it's first three elements
x[:3]

#Given the X numpy array, show all middle elements
x[1:-1]

#Given the X numpy array, show the elements in reverse position
x[::-1]

#Given the X numpy array, show the elements in an odd position
x[::2]

#Given the X numpy matrix, show the first row elements
x=np.arange(9).reshape(3,3)
x[0]

#Given the X numpy matrix, show the last row elements
x[-1]

#Given the X numpy matrix, show the first element on first row
x=np.arange(8).reshape(2,4)
print(x[0,0])

#Given the X numpy matrix, show the last element on last row
print(x[-1,-1])

#Given the X numpy matrix, show the middle row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
print(X[2:3])

#Given the X numpy matrix, show the first two elements on the first two rows
print(X[0:2,0:2])

#Given the X numpy matrix, show the last two elements on the last two rows
X[-2:,-2:]

0
7
[[ 9 10 11 12]]
[[1 2]
 [5 6]]


array([[11, 12],
       [15, 16]])

In [141]:
#Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]
np.array(X, float)

#Reverse the given numpy array (first element becomes last)
X[::-1]

#Order (sort) the given numpy array
X.sort()
X

#Given the X numpy array, set the fifth element equal to 1
X[4] = 1
X

#Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])
X[3] = 40
X

#Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1:,:] =[1,1,1,1]
X

#Given the X numpy matrix, change the last item on the last row with a 0
X[-1,-1] = 0
X

#Given the X numpy matrix, add 5 to every element
X=X+5
X

#Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X

#Given the X numpy array, get the negative elements
X[mask]

#Given the X numpy array, get numbers higher than 5
mask = X > 5
X[mask]

#Given the X numpy array, get numbers higher than the elements mean
m=X.mean()
X[X>m]

#Given the X numpy array, get numbers equal to 2 or 10
m =(X==2) |(X==10)
X[m]

#Given the X numpy array, return True if none of its elements is zero
X.all()

#Given the X numpy array, return True if any of its elements is zero
X.any()

#Given the X numpy array, show the sum of its elements
X.sum()

#Given the X numpy array, show the mean value of its elements
X.mean()

#Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

#Given the X numpy matrix, show the mean value of its rows
X.sum(axis=1)

#Given the X numpy array, show the max value of its elements
X.max()

16

# Numpy Excercise 2

In [19]:
#Exercise 1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

#Exercise 2. How to create a 1D array?
a=np.array([1,2,3,4])

#Exercise 3. How to create a boolean array?
a>=3
# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

#Exercise 4. How to extract items that satisfy a given condition from 1D array?
a[a>=3]

#Exercise 5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr>4] = 1
arr
#Exercise 6. How to replace items that satisfy a condition without affecting the original array?
a=np.copy(arr)

#Exercise 7. How to reshape an array?
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,3)

#Exercise 8. How to stack two arrays vertically?
a=[1,2,3]
b=[2,3,5]
np.vstack((a,b))
#Exercise 9. How to stack two arrays horizontally?
np.hstack((a,b))
#Exercise 10. How to generate custom sequences in numpy without hardcoding?-----------imp
np.repeat(b,3)
np.tile(a,3)
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

#Exercise 11. How to get the common items between two python numpy arrays?------------imp
a=np.array([1,2,3])
b=np.array([3,2,5])
np.intersect1d(a,b)

#Exercise 12. How to remove from one array those items that exist in another?------------imp
np.setdiff1d(b,a)

#Exercise 13. How to get the positions where elements of two arrays match?------------imp
np.where(a == b)

#Exercise 14. How to extract all numbers between a given range from a numpy array?

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

#Exercise 15. How to make a python function that handles scalars to work on numpy arrays?
def m(a,b):
    mmm= [mm(x,y) for x,y in map(lambda x,y:(x,y) ,a,b)]
    return mmm

    
def mm(x,y):
    if x>y:
        return x
    else :
        return y
y = np.array([5, 7, 9, 8, 6, 4, 5])
x = np.array([6, 3, 4, 8, 9, 7, 1])

print(m(x,y))

#Exercise 16. How to swap two columns in a 2d numpy array?
a=np.arange(9).reshape(3,3)
a[:,[1,2]] = a[:,[2,1]]
print(a)

#Exercise 17. How to swap two rows in a 2d numpy array?
#similar as columns

#Exercise 18. How to reverse the rows of a 2D array?
a[::-1,:]

#Exercise 19. How to reverse the columns of a 2D array?
a[:,::-1]

#Exercise 20. How to create a 2D array containing random floats between 5 and 10?
a=np.random.uniform(5,10, size=(5,3))

#Exercise 21. How to print only 3 decimal places in python numpy array?
np.set_printoptions(precision=2)
print(np.array([1.4637,1.5497,5.34964]))

#Exercise 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr
np.set_printoptions(suppress=True)
print(rand_arr)

#Exercise 23. How to limit the number of items printed in output of numpy array?
l=np.arange(9)
np.set_printoptions(threshold=True)
l

#Exercise 24. How to print the full numpy array without truncating
a = np.arange(15)
np.set_printoptions(threshold=True)
a

#Exercise 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
#iris_data = np.genfromtxt('../input/iris/Iris.csv', delimiter=',', skip_header=1, 
 #                         usecols = [0,1,2,3,4,5], dtype = object)
#iris_data

#Exercise 26. How to extract a particular column from 1D array of tuples?

#Exercise 27. How to convert a 1d array of tuples to a 2d numpy array?

#xercise 28. How to compute the mean, median, standard deviation of a numpy array?
a=np.array([4,6,2,4,9])
np.mean(a)
np.median(a)
np.std(a)

#Exercise 29. How to normalize an array so the values range exactly between 0 and 1?

#Exercise 30. How to compute the softmax score?
softmax = np.exp(iris_data)/sum(np.exp(iris_data))

#Exercise 31. How to find the percentile scores of a numpy array?
#numpy.percentile()
# percentile of 10 ,  would indicate 10 jo hai woh 80% of valuesse bada hai 
    
#Exercise 32. How to insert values at random positions in an array

#Exercise 33. How to find the position of missing values in numpy array?
res = np.argwhere(np.isnan(arr))

#Exercise 34. How to filter a numpy array based on two or more conditions? 
iris_data[(iris_data[:, 2] > 1.5) & (iris_data[:, 0] < 5.0)]

#Exercise 35. How to drop rows that contain a missing value from a numpy array?
#Exercise 36. How to find the correlation between two columns of a numpy array?
#Exercise 43. How to get the second largest value of an array when grouped by another array?
#Exercise 44. How to sort a 2D array by a column
#Exercise 45. How to find the most frequent value in a numpy array?

#print(np.bincount(x).argmax())

#Exercise 46. How to find the position of the first occurrence of a value greater than a given value?
#Exercise 47. How to replace all values greater than a given value to a given cutoff?
#Exercise 48. How to get the positions of top n values from a numpy array?
#Exercise 49. How to compute the row wise counts of all possible values in an array?
#Exercise 50. How to convert an array of arrays into a flat 1d array?


1.21.5
[6, 7, 9, 8, 9, 7, 5]
[[0 2 1]
 [3 5 4]
 [6 8 7]]
[1.46 1.55 5.35]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.3664319132398464

[6, 7, 9, 8, 9, 7, 5]


## Array Manipulation

In [5]:
a=np.array([1,2,3])
b=np.array([3,4,5])
np.concatenate((a,b))

array([1, 2, 3, 3, 4, 5])

In [9]:
np.vstack((a,b))

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
np.hstack((a,b))

array([1, 2, 3, 3, 4, 5])

In [8]:
np.column_stack((a,b))

array([[1, 3],
       [2, 4],
       [3, 5]])

## Indexing and Slicing

In [11]:
a=np.array([[1,1,1],[3,3,3],[4,4,4]])
print(a)

[[1 1 1]
 [3 3 3]
 [4 4 4]]


In [16]:
print(a[0])
print(a[:2])
#print(a[:1,1:])
#print(a[:2,1:])
print(a[1:,1:])


[1 1 1]
[[1 1 1]
 [3 3 3]]
[[3 3]
 [4 4]]


# Scipy and its sub packages

In [ ]:
## Scipy.cluster
## scipy.stats
## scipy.optimize
## scipy.integrate
## scipy.linalg
## scipy.fftpack
## scipy.signal


# Pandas
### 1D - Series
### 2D - Dataframe
### 3D - Panel Data

In [1]:
import pandas as pd

In [6]:
a=[1,3,'c']
b=pd.Series(a)
print(b)



0    1
1    3
2    c
dtype: object


### DataFrames can be created from List ,Series, Dictionary, numpy array
### In Pandas upper limit is included ,unlike python list and numpy arrays  

### Series and Dataframe Excercise 

In [23]:
import pandas as pd
#Create an empty pandas Series

#Given the X python list convert it to an Y pandas Series
X = ['A','B','C']
Y= pd.Series(X)
print(Y)

#Given the X pandas Series, name it 'My letters'
X = pd.Series(['A','B','C'])
X.name = 'My letters'

#Given the X pandas Series, show its values
X = pd.Series(['A','B','C'])
X.values

#Assign index names to the given X pandas Series
X.index=['first', 'second', 'third']

#Given the X pandas Series, show its first element
X.loc['first']

#Given the X pandas Series, show all middle elements
X[1:-1]

#Given the X pandas Series, show the first and last elements
X[[0,-1]]

#Order (sort) the given pandas Series
X = pd.Series([4,2,5,1,3],index=['forth','second','fifth','first','third'])
X = X.sort_values()
X

#Given the X pandas Series, change all the middle elements to 0
X[1:-1] = 0
print(X)

#Given the X pandas Series, make a mask showing negative elements
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
X[X<0]
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

#Given the X pandas Series, return True if none of its elements is zero
X.all()

#df.drop(df.index[2:4], inplace=True)
#df.drop([5,6], axis=0, inplace=True)
#df = df.drop(columns=['gender'])

0    A
1    B
2    C
dtype: object
first     1
second    0
third     0
forth     0
fifth     5
dtype: int64


False

In [38]:
import numpy as np
import pandas as pd 

#Empty Dataframe
pd.DataFrame(data=[None],
             index=[None],
             columns=[None])

#Create a marvel_df pandas DataFrame with the given marvel data
marvel_data = [
    ['Spider-Man', 'male', 1962],
    ['Captain America', 'male', 1941],
    ['Wolverine', 'male', 1974],
    ['Iron Man', 'male', 1963],
    ['Thor', 'male', 1963],
    ['Thing', 'male', 1961],
    ['Mister Fantastic', 'male', 1961],
    ['Hulk', 'male', 1962],
    ['Beast', 'male', 1963],
    ['Invisible Woman', 'female', 1961],
    ['Storm', 'female', 1975],
    ['Namor', 'male', 1939],
    ['Hawkeye', 'male', 1964],
    ['Daredevil', 'male', 1964],
    ['Doctor Strange', 'male', 1963],
    ['Hank Pym', 'male', 1962],
    ['Scarlet Witch', 'female', 1964],
    ['Wasp', 'female', 1963],
    ['Black Widow', 'female', 1964],
    ['Vision', 'male', 1968]
]
marvel_df = pd.DataFrame(data=marvel_data)

marvel_df.columns= ['Name', 'Gender' , 'Year']
marvel_df.index=marvel_df['Name']
marvel_df= marvel_df.drop(['Name'],axis = 1)
marvel_df = marvel_df.drop(['Namor', 'Hank Pym'], axis=0)
marvel_df.iloc[:5]

marvel_df.iloc[-5:]

marvel_df.iloc[:5]['Gender']
marvel_df.iloc[1:-1]['Year'].to_frame()
marvel_df.iloc[::len(marvel_df)-1]
#OR
marvel_df.iloc[[0, -1]]

marvel_df.loc['Vision','Year'] = 1964 

marvel_df['years_since']=2024 - marvel_df['Year']
marvel_df

marvel_df[marvel_df['Gender']=='female']

marvel_df[marvel_df['Year']>1970]

Gender  Year  years_since
Name                                
Wolverine    male  1974           50
Storm      female  1975           49

## Merge , Join and Concatenate DataFrames

In [11]:
import pandas as pd
player = ['Player1' , 'Player2','Player']
point = [8,9,6]
title=['Game1','Game2','Game3']
df1 = pd.DataFrame({"Player":player,"Points":point,"Title":title})
df1


Player  Points  Title
0  Player1       8  Game1
1  Player2       9  Game2
2   Player       6  Game3

In [9]:
player= ["Player1","Player5", "Player6"]
power = ['Punch',"Kick","Elbow"]
title = ['Game1','Game5','Game6']
df2 = pd.DataFrame({'Player':player,"Power":power,"Title":title})
df2

Player  Power  Title
0  Player1  Punch  Game1
1  Player5   Kick  Game5
2  Player6  Elbow  Game6

In [12]:
# Inner Merge
df1.merge(df2,on="Player",how="inner")

Player  Points Title_x  Power Title_y
0  Player1       8   Game1  Punch   Game1

In [13]:
# Left/Right/Outer Merge
df1.merge(df2,on="Player", how='left')

Player  Points Title_x  Power Title_y
0  Player1       8   Game1  Punch   Game1
1  Player2       9   Game2    NaN     NaN
2   Player       6   Game3    NaN     NaN

### How to perform Join Opertion in Pandas
### It is must to havecommon index 

In [38]:
player = ['Player1' , 'Player2','Player']
point = [8,9,6]
title=['Game1','Game2','Game3']
df3 = pd.DataFrame({"Players":player,"Points":point,"Title":title},index = ['L1' , 'L2' , 'L3'])
df3

Players  Points  Title
L1  Player1       8  Game1
L2  Player2       9  Game2
L3   Player       6  Game3

In [34]:
player= ["Player1","Player5", "Player6"]
power = ['Punch',"Kick","Elbow"]
title = ['Game2','Game5','Game6']
df4 = pd.DataFrame({'Player':player,"Power":power,"Titles":title} , index= ['L2','L3', 'L4'])
df4

Player  Power Titles
L2  Player1  Punch  Game2
L3  Player5   Kick  Game5
L4  Player6  Elbow  Game6

In [39]:
# inner join
df3.join(df4,how='inner')

Players  Points  Title   Player  Power Titles
L2  Player2       9  Game2  Player1  Punch  Game2
L3   Player       6  Game3  Player5   Kick  Game5

In [ ]:
# left/inner/outer join


### How to concatenate 2 dataframe in pandas 

In [25]:
pd.concat([df3,df4])

Player  Points  Title  Power
L1  Player1     8.0  Game1    NaN
L2  Player2     9.0  Game2    NaN
L3   Player     6.0  Game3    NaN
L2  Player1     NaN  Game2  Punch
L3  Player5     NaN  Game5   Kick
L4  Player6     NaN  Game6  Elbow

## Importing and Analysing the Dataset 
## Cleaning the Dataset

# Visualization

In [25]:
import pandas as pd

df = pd.read_csv(r'C:\Users\MANSI\Desktop\mydata.csv')
df.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [26]:
# Handling Columns
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
df.rename(columns = {})

# Covariance 
## Its helps us quantify the the relationship between features
## When X is increasing and Y is also increasing -> COV is +ve
## When X is increasing and Y is decreasing -> COV is -ve
## If COV is ~0  it means no relation b/w X and Y

## Pearson's Covariance Co-efficicent


# Corelation
## Pearson Correlation

# Curse of Dimentionality  

## Why Dimensionlity Reduction
### -->Prevent the curse of Dimentionlity
### -->Improve the performance of the model
### --> Visualize the data , ie understand the data 

## Two Ways to remove it 

### 1. Feature Selection  
#### -> Take important features 

### 2. Dimentionality Reduction  
#### -> Feature Extraction - Taeke essence from orginal 
#### -> PCA (Principal Component Analysis)
####    Projection
####    Cost Function (i.e.Variance)

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd



In [12]:
## load the dataset
from sklearn.datasets import load_breast_cancer

In [18]:
cancer_dataset=load_breast_cancer()

In [19]:
cancer_dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])